const $=s=>document.querySelector(s),fmt=n=>n.toLocaleString('en-US');
const PR=[{n:'Lawcare Mixture',c:'LCM',u:'Pieces',k:'Cartons',f:20,a:1},{n:'Lawson Mixture',c:'LWM',u:'Pieces',k:'Cartons',f:60,a:1},{n:'Delayman Capsules',c:'DMC',u:'Packs',k:'Cartons',f:20,a:1}];
const DEST=['Headquarters','Accra'];let ME='Admin User';
const B={LC170926:{p:0,s:'Finished'},LW160926:{p:1,s:'Finished'},DM150926:{p:2,s:'Finished'},LW190926:{p:1,s:'Unfinished'}};
// t: O opening, P production, D distribution, R usable return, X unusable return, A adjustment
let M=[['2026-09-01','LC170926','O',500,'Carry forward','Stock Officer'],['2026-09-17','LC170926','P',1000,'Production line 1','Stock Officer'],['2026-09-17','LC170926','D',700,'Accra','Stock Officer'],['2026-09-20','LC170926','R',50,'Customer · Usable','Stock Officer'],['2026-09-21','LC170926','X',12,'Customer · Leaking','Stock Officer'],
['2026-09-01','LW160926','O',300,'Carry forward','Stock Officer'],['2026-09-16','LW160926','P',600,'Production line 2','Stock Officer'],['2026-09-18','LW160926','D',240,'Headquarters','Stock Officer'],['2026-09-19','LW190926','P',250,'Awaiting packaging','Stock Officer'],
['2026-09-01','DM150926','O',200,'Carry forward','Stock Officer'],['2026-09-15','DM150926','P',800,'Production line 3','Stock Officer'],['2026-09-22','DM150926','D',300,'Headquarters','Stock Officer'],['2026-09-28','DM150926','X',8,'Branch · Expired','Stock Officer']];
const pr=b=>PR[B[b].p],sum=(b,t)=>M.filter(m=>m[1]==b&&m[2]==t).reduce((a,m)=>a+m[3],0);
const st=b=>{const o=sum(b,'O'),p=sum(b,'P'),r=sum(b,'R'),d=sum(b,'D'),ad=sum(b,'A'),av=o+p+r+ad;return{o,p,r,d,av,c:av-d,x:sum(b,'X')}};
const tot=s=>Object.keys(B).filter(b=>B[b].s==s).reduce((a,b)=>a+st(b).c,0);
const sb=s=>`<span class="bd ${s=='Finished'?'g':'o'}">${s}</span>`;
const TYPE={O:['Opening Stock','gr'],P:['Production','b'],D:['Distribution','p'],R:['Return','g'],X:['Return (unusable)','r'],A:['Adjustment','o']};
const tb=t=>`<span class="bd ${TYPE[t][1]}">${TYPE[t][0]}</span>`;
const NAV=[['dashboard','Dashboard','▦'],['products','Products','❖'],['opening','Opening Stock','◧'],['production','Production','⚙'],['distribution','Distribution','➜'],['returns','Returns','↺'],['stock','Stock / Inventory','▤'],['movements','Stock Movements','⇅'],['reports','Reports','▧']];
let tab='All',q='',fp='',mt='',sel='';
const leaf=`<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2"><path d="M5 19C5 10 10 5 20 4c0 10-5 15-14 15zM5 19l8-8"/></svg>`;
function toast(m,e){const d=document.createElement('div');d.textContent=m;if(e)d.className='e';$('#toast').append(d);setTimeout(()=>d.remove(),3500)}
function shell(t,body){const pg=location.hash.slice(2).split('/')[0]||'dashboard';return`<aside id="side"><div class="logo"><i>${leaf}</i><div><b>HERBAL STOCK</b><small>Management System</small></div></div>${NAV.map(n=>`<a href="#/${n[0]}" class="${pg==n[0]?'on':''}" onclick="$('#side').classList.remove('open')"><span>${n[2]}</span>${n[1]}</a>`).join('')}<div class="sp"></div><a href="#/profile"><span>◉</span>User Profile</a><a href="#/settings"><span>⚒</span>Settings</a><button class="nb" onclick="location.hash='#/login'"><span>⏻</span>Logout</button></aside><main><div class="top"><button class="ic ham" aria-label="Menu" onclick="$('#side').classList.toggle('open')">☰</button><div><h1>${t}</h1><small>Herbal Management / ${t}</small></div><div class="sp" style="flex:1"></div><button class="ic" aria-label="Search" onclick="gs()">⌕</button><button class="ic" aria-label="Notifications" onclick="nt()">🔔<i class="dot"></i></button><div class="user"><div class="t"><b>${ME}</b><br><small style="color:var(--mut)">Stock Officer</small></div><div class="av">AU</div></div></div><div id="dd"></div><div class="pg">${body}</div></main>`}
function nt(){const d=$('#dd');if(d.innerHTML){d.innerHTML='';return}d.innerHTML=`<div class="dd"><div><b>Low stock warning</b><small>Lawson Mixture LW190926 (unfinished) below 300 pcs</small></div><div><b>Return requires review</b><small>DM150926 · 8 packs expired, not added to stock</small></div><div><b>Distribution recorded</b><small>300 packs to Headquarters · 22 Sep</small></div><div><b>Production recorded</b><small>LW190926 · 250 pcs unfinished</small></div></div>`}
function gs(){modal(`<h3>Search batch</h3><input id="gsb" placeholder="Batch number e.g. LC170926" style="width:100%" list="bl"><datalist id="bl">${Object.keys(B).map(b=>`<option>${b}</option>`)}</datalist><div class="act"><button class="btn s" onclick="cm()">Cancel</button><button class="btn" onclick="gb($('#gsb').value)">Open batch</button></div>`)}
function gb(v){v=v.trim().toUpperCase();if(!B[v])return toast('Batch '+v+' not found.',1);cm();location.hash='#/batch/'+v}
function modal(h){cm();const d=document.createElement('div');d.className='ov';d.id='mo';d.innerHTML=`<div class="md" role="dialog">${h}</div>`;document.body.append(d)}function cm(){$('#mo')?.remove()}
const opt=a=>a.map(x=>`<option>${x}</option>`).join(''),bo=()=>Object.keys(B).map(b=>`<option value="${b}">${b} · ${pr(b).n}</option>`).join('');
const kpi=(l,v,u,s,c)=>`<div class="card kpi" style="--c:${c}"><small>${l}</small><div class="v">${fmt(v)} <span>${u}</span></div><em>${s}</em></div>`;
const today=M.filter(m=>m[0]=='2026-09-17');
function calc(s){return`<div class="calc"><div><small>Opening</small><b>${fmt(s.o)}</b></div><div class="op">+</div><div><small>Production</small><b>${fmt(s.p)}</b></div><div class="op">+</div><div><small>Usable returns</small><b>${fmt(s.r)}</b></div><div class="op">=</div><div class="hl"><small>Available</small><b>${fmt(s.av)}</b></div></div><div class="calc" style="margin-top:8px"><div class="hl"><small>Available</small><b>${fmt(s.av)}</b></div><div class="op">−</div><div><small>Distribution</small><b>${fmt(s.d)}</b></div><div class="op">=</div><div class="hl"><small>Closing stock</small><b>${fmt(s.c)}</b></div></div>${s.x?`<div class="al o">Unusable returns (${s.x}) are excluded from these figures.</div>`:''}`}
function stockRows(f){return Object.keys(B).filter(f).map(b=>({b,s:st(b),p:pr(b)}))}
function stockTable(rows,full){const h=full?'Usable Returns':'Returns';return`<div class="stk"><div class="tw"><table><thead><tr><th>Product</th><th>Batch No.</th><th>Status</th><th class="n">Opening</th><th class="n">Produced</th><th class="n">${h}</th><th class="n">Available</th><th class="n">Distributed</th><th class="n">Closing</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r.p.n}</b></td><td><a href="#/batch/${r.b}">${r.b}</a></td><td>${sb(B[r.b].s)}</td><td class="n">${fmt(r.s.o)}</td><td class="n">${fmt(r.s.p)}</td><td class="n">${fmt(r.s.r)}</td><td class="n k">${fmt(r.s.av)}</td><td class="n">${fmt(r.s.d)}</td><td class="n k">${fmt(r.s.c)}</td></tr>`).join('')||`<tr><td colspan=9><div class="empty"><b>No stock found</b>Try a different filter.</div></td></tr>`}</tbody></table></div><div class="mob">${rows.map(r=>`<div class="card"><b>${r.p.n}</b> ${sb(B[r.b].s)}<br><a href="#/batch/${r.b}">${r.b}</a><div style="display:flex;justify-content:space-between;margin-top:8px"><span>Available<br><b class="q">${fmt(r.s.av)}</b></span><span>Distributed<br><b>${fmt(r.s.d)}</b></span><span>Closing<br><b class="q">${fmt(r.s.c)}</b></span></div></div>`).join('')}</div></div>`}
function filt(){return`<div class="fl"><input placeholder="Search batch…" value="${q}" oninput="q=this.value;go(1)"><select onchange="fp=this.value;go(1)"><option value="">All products</option>${PR.map((p,i)=>`<option value="${i}" ${fp==i&&fp!==''?'selected':''}>${p.n}</option>`)}</select><select><option>Sep 2026</option><option>Aug 2026</option></select></div>`}
const ff=b=>(!q||b.includes(q.toUpperCase()))&&(fp===''||B[b].p==fp)&&(tab=='All'||B[b].s==tab);
function chart(){const days=['15','16','17','18','19','20','22'],pv=[800,600,1000,0,250,0,0],dv=[0,0,700,240,0,0,300],mx=1000;return`<div class="bars">${days.map((d,i)=>`<div><div class="pr"><i style="height:${pv[i]/mx*100}%;background:var(--b)"></i><i style="height:${dv[i]/mx*100}%;background:var(--p)"></i></div>${d} Sep</div>`).join('')}</div><small><span class="bd b">Production</span> <span class="bd p">Distribution</span></small>`}
function pieBars(){const ps=PR.map((p,i)=>[p.n,Object.keys(B).filter(b=>B[b].p==i).reduce((a,b)=>a+st(b).c,0)]),m=Math.max(...ps.map(x=>x[1]));return ps.map(x=>`<div style="margin:10px 0"><div style="display:flex;justify-content:space-between"><span>${x[0]}</span><b>${fmt(x[1])}</b></div><div style="background:var(--grl);border-radius:6px"><div style="height:10px;border-radius:6px;background:var(--g);width:${x[1]/m*100}%"></div></div></div>`).join('')}
function dash(){const fs=tot('Finished'),us=tot('Unfinished');const ur=sum('LC170926','R');return kpi('Finished stock',fs,'pcs/packs','Across 3 products','var(--g)').replace('','')&&`<div class="kpis">${kpi('Finished stock',fs,'units','Across 3 products','var(--g)')}${kpi('Unfinished stock',us,'units','Awaiting packaging','var(--o)')}${kpi("Today's production",1000,'pcs','Lawcare Mixture','var(--b)')}${kpi("Today's distribution",700,'pcs','To Accra','var(--p)')}${kpi('Usable returns',50,'pcs','Can be added to stock','var(--g)')}${kpi('Unusable returns',20,'units','Damaged / expired / leaking','var(--r)')}</div><div class="card"><div class="hd"><h2 style="font-size:16px">Current stock overview</h2></div>${filt()}${stockTable(stockRows(ff),0)}</div><div class="grid"><div class="card"><b>Production vs distribution</b>${chart()}</div><div class="card"><b>Stock by product</b>${pieBars()}</div><div class="card"><b>Movement summary</b><div style="margin-top:10px;display:grid;gap:8px">${['P','D','R','A'].map(t=>`<div style="display:flex;justify-content:space-between">${tb(t)}<b>${fmt(M.filter(m=>m[2]==t).reduce((a,m)=>a+m[3],0))}</b></div>`).join('')}</div></div></div>`}
function dtable(head,rows,emp,btn){return rows.length?`<div class="tw"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:`<div class="empty"><b>No ${emp} records found</b>${emp[0].toUpperCase()+emp.slice(1)} records for the selected period will appear here.<br><br>${btn||''}</div>`}
const dt=s=>new Date(s).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});
const rec=(t,h,lbl,btn)=>`<div class="hd"><h2>${lbl}</h2><button class="btn" onclick="${btn}()">+ Record ${lbl=='Opening Stock'?'Opening Stock':lbl=='Production'?'Production':lbl=='Distribution'?'Distribution':'Return'}</button></div><div class="card"><div class="fl"><input type="date"><select onchange="fp=this.value;go(1)"><option value="">All products</option>${PR.map((p,i)=>`<option value="${i}">${p.n}</option>`)}</select><input placeholder="Batch" oninput="q=this.value;go(1)"></div>${t}</div>`;
const lst=(types)=>M.filter(m=>types.includes(m[2])&&(!q||m[1].includes(q.toUpperCase()))&&(fp===''||B[m[1]].p==fp));
function prods(){return`<div class="hd"><h2>Products</h2><button class="btn" onclick="addP()">+ Add Product</button></div><div class="card">${dtable(['Product','Code','Unit','Conversion','Status','Actions'],PR.map((p,i)=>[`<b>${p.n}</b>`,p.c,p.k+' / '+p.u,`1 Carton = ${p.f} ${p.u}`,`<span class="bd ${p.a?'g':'gr'}">${p.a?'Active':'Inactive'}</span>`,`<button class="btn s sm" onclick="toast('${p.n}: ${p.k} / ${p.u}')">View</button> <button class="btn s sm" onclick="addP(${i})">Edit</button> <button class="btn s sm" onclick="PR[${i}].a^=1;go()">${p.a?'Deactivate':'Activate'}</button>`]),'product')}</div>`}
function addP(i){const p=i==null?{n:'',c:'',u:'Pieces',k:'Cartons',f:20}:PR[i];modal(`<h3>${i==null?'Add product':'Edit product'}</h3><div class="fg"><label>Product name <span class="req">*</span><input id="pn" value="${p.n}" placeholder="e.g. Lawcare Mixture"></label><label>Product code <span class="req">*</span><input id="pc" value="${p.c}" placeholder="LCM"></label><label>Primary (base) unit<select id="pu"><option>Pieces</option><option>Packs</option></select></label><label>Secondary unit<select><option>Cartons</option></select></label><label class="w">Conversion quantity<input id="pf" type="number" min="1" value="${p.f}" oninput="$('#cp').textContent='1 Carton = '+this.value+' '+$('#pu').value"></label><div class="al g w" id="cp">1 Carton = ${p.f} ${p.u}</div><label class="w">Description<textarea rows=2></textarea></label><label><input type="checkbox" checked style="width:auto"> Active</label></div><div class="act"><button class="btn s" onclick="cm()">Cancel</button><button class="btn" onclick="sp(${i})">Save product</button></div>`)}
function sp(i){const n=$('#pn').value.trim(),c=$('#pc').value.trim();if(!n||!c)return toast('Product name and code are required.',1);const o={n,c,u:$('#pu').value,k:'Cartons',f:+$('#pf').value,a:1};i==null?PR.push(o):PR[i]=o;cm();toast('Product saved successfully.');go()}
// generic entry form: type 'O','P','D','R'
function conv(){const p=PR[B[$('#fb').value]?.p??0],u=$('#fu')?.value,v=+$('#fq').value||0;return u=='Cartons'?v*p.f:v}
function unitOpts(){const p=PR[B[$('#fb')?.value||Object.keys(B)[0]].p];return`<option>${p.u}</option><option>Cartons</option>`}
function upd(){const t=$('#ft').value,b=$('#fb').value,p=PR[B[b].p],n=conv();$('#fu').innerHTML=unitOpts().replace(`<option>${$('#fu').value}</option>`,`<option selected>${$('#fu').value}</option>`);$('#fu').value=$('#fu').dataset.v||p.u;let h='';if($('#fu').value=='Cartons')h=`Equivalent: ${fmt(n)} ${p.u}`;if(t=='D'){const a=st(b).av-st(b).d;h+=` <div class="al ${n>a?'r':'g'}">Available: ${fmt(a)} ${p.u}${n?(n>a?` — Insufficient stock. Available quantity: ${fmt(a)} ${p.u.toLowerCase()}.`:` · Remaining after distribution: ${fmt(a-n)} ${p.u}`):''}</div>`;$('#fs').disabled=!n||n>a}
if(t=='R'){const c=$('#fc').value,ok=c=='Usable';h+=`<div class="al ${ok?'g':'r'}">${ok?'Usable return: choose "Add to usable stock" after authorization.':'This quantity will NOT automatically be added to usable stock.'}</div>`}$('#fh').innerHTML=h}
function form(t,title){const ex={O:'',P:`<label>Production status<select id="fst"><option>Finished</option><option>Unfinished</option></select></label>`,D:`<label>Destination<select id="fx">${opt(DEST)}</select></label><button class="btn s sm" style="align-self:end" onclick="DEST.push(prompt('New destination')||'x');DEST.pop()||0;">+ Destination</button>`,R:`<label>Returned from<select id="fx" onchange="$('#so').hidden=this.value!='Other'"><option>Branch</option><option>Customer</option><option>Distributor</option><option>Other</option></select></label><label id="so" hidden>Specify source<input></label><label>Reason<select><option>Damaged</option><option>Excess</option><option>Leakage</option><option>Expired</option><option>Other</option></select></label><label>Condition<select id="fc" onchange="upd()"><option>Usable</option><option>Damaged</option><option>Expired</option><option>Leaking</option><option>Unusable</option><option>Other</option></select></label>`};
modal(`<h3>${title}</h3><input type="hidden" id="ft" value="${t}"><div class="fg"><label>Date <span class="req">*</span><input type="date" id="fd" value="2026-09-30"></label><label>Batch number <span class="req">*</span>${t=='P'||t=='O'?`<input id="fb" list="bl2" placeholder="e.g. LC170926" oninput="upd()"><datalist id="bl2">${Object.keys(B).map(b=>`<option>${b}</option>`)}</datalist>`:`<select id="fb" onchange="upd()">${bo()}</select>`}</label><label>Quantity <span class="req">*</span><input id="fq" type="number" min="1" placeholder="0" oninput="upd()"></label><label>Unit<select id="fu" onchange="this.dataset.v=this.value;upd()"></select></label>${ex[t]||''}${t=='O'?`<label>Stock status<select id="fst"><option>Finished</option><option>Unfinished</option></select></label>`:''}<label class="w">Remarks<input placeholder="Optional"></label></div><div id="fh"></div><div class="act"><button class="btn s" onclick="cm()">Cancel</button><button class="btn" id="fs" onclick="save()">${t=='D'?'Review distribution':'Save record'}</button></div>`);if(!$('#fb').value&&$('#fb').tagName=='SELECT')$('#fb').selectedIndex=0;$('#fu').innerHTML=unitOpts();upd()}
function save(){const t=$('#ft').value,b=$('#fb').value.trim().toUpperCase(),n=conv();if(!B[b]&&t=='P'){return toast('Enter an existing batch or add product mapping first.',1)}if(!n||n<1)return toast('Enter a valid quantity.',1);const p=pr(b);
if(t=='D'){return modal(`<h3>Confirm distribution</h3><div class="card">Product: <b>${p.n}</b><br>Batch: <b>${b}</b><br>Quantity: <b>${fmt(n)} ${p.u}</b><br>Destination: <b>${$('#fx').value}</b><br>Available: ${fmt(st(b).av-st(b).d)} ${p.u}<br>Remaining: <b>${fmt(st(b).av-st(b).d-n)} ${p.u}</b></div><div class="act"><button class="btn s" onclick="cm()">Cancel</button><button class="btn" onclick="commit('D',${n},'${b}','${$('#fx').value}')">Confirm distribution</button></div>`)}
if(t=='R'){const c=$('#fc').value;if(c=='Usable')return modal(`<h3>Add to usable stock?</h3><p>${fmt(n)} ${p.u} of ${b} will be added to Available stock. This needs stock officer authorization.</p><div class="act"><button class="btn s" onclick="commit('X',${n},'${b}','${$('#fx').value} · Usable (pending)');">Keep pending</button><button class="btn" onclick="commit('R',${n},'${b}','${$('#fx').value} · Usable')">Add to usable stock</button></div>`);return commit('X',n,b,$('#fx').value+' · '+c)}
commit(t,n,b,t=='P'?'Production':'Carry forward')}
function commit(t,n,b,x){M.push(['2026-09-30',b,t,n,x,ME]);cm();toast({P:'Production recorded successfully.',D:'Distribution recorded successfully.',R:'Return added to usable stock.',X:'Return recorded. Not added to usable stock.',O:'Opening stock saved.'}[t]);go()}
function mtable(types,cols){const r=lst(types);return dtable(cols,r.map(m=>{const p=pr(m[1]);return[dt(m[0]),p.n,`<a href="#/batch/${m[1]}">${m[1]}</a>`,fmt(m[3]),p.u,...(types.includes('D')?[m[4],m[5],'<span class="bd g">Completed</span>']:types.includes('R')?[m[4],'',m[2]=='R'?'<span class="bd g">Usable</span>':'<span class="bd r">Unusable</span>',m[2]=='R'?'<span class="bd g">Added to stock</span>':'<span class="bd gr">No stock effect</span>']:[sb(B[m[1]].s),m[5],''])]}),types.includes('D')?'distribution':types.includes('R')?'return':'production',`<button class="btn" onclick="form('${types[0]}','Record')">+ Record</button>`)}
function opening(){return`<div class="al g" style="margin:0 0 12px">Last period's closing stock can become this period's opening stock automatically. <button class="btn sm" style="margin-left:8px" onclick="cf()">Carry Forward Previous Closing Stock</button></div>`+rec(mtable(['O'],['Date','Product','Batch No.','Quantity','Unit','Status','Added By','Actions']),0,'Opening Stock','fo')}
function cf(){modal(`<h3>Carry forward closing stock?</h3><p>This creates opening records for ${Object.keys(B).length} batches using their current closing balance.</p><table style="min-width:0">${Object.keys(B).map(b=>`<tr><td>${b}</td><td class="n">${fmt(st(b).c)}</td></tr>`).join('')}</table><div class="act"><button class="btn s" onclick="cm()">Cancel</button><button class="btn" onclick="cm();toast('Closing stock carried forward as opening stock.')">Confirm carry forward</button></div>`)}
const fo=()=>form('O','Add opening stock'),fpd=()=>form('P','Record production'),fd=()=>form('D','Record distribution'),fr=()=>form('R','Record return');
function stock(){return`<div class="hd"><h2>Stock / Quantity Available</h2><div class="fl" style="margin:0"><input id="sb" placeholder="Search batch no." list="bl3" onkeydown="if(event.key=='Enter')gb(this.value)"><datalist id="bl3">${Object.keys(B).map(b=>`<option>${b}`)}</datalist><button class="btn" onclick="gb($('#sb').value)">Search batch</button></div></div><div class="kpis">${kpi('Finished stock',tot('Finished'),'units','Usable','var(--g)')}${kpi('Unfinished stock',tot('Unfinished'),'units','Not yet sellable','var(--o)')}</div><div class="card"><div class="tabs">${['All','Finished','Unfinished'].map(t=>`<button class="${tab==t?'on':''}" onclick="tab='${t}';go()">${t=='All'?'All Stock':t}</button>`).join('')}</div>${filt()}${stockTable(stockRows(ff),1)}<p style="color:var(--mut);font-size:12px">Damaged, expired, leaking and unusable returns are excluded from usable stock.</p></div>`}
function batch(b){if(!B[b])return`<div class="empty"><b>Batch not found</b>Check the batch number and try again.</div>`;const s=st(b),p=pr(b);let bal=0;const ev=M.filter(m=>m[1]==b).sort((a,c)=>a[0]<c[0]?-1:1);return`<div class="hd"><h2>Batch ${b}</h2><a href="#/stock" class="btn s" style="text-decoration:none">← Back to stock</a></div><div class="kpis"><div class="card"><small>Product</small><div class="v" style="font-size:18px;font-weight:700">${p.n}</div></div><div class="card"><small>Current status</small><div>${sb(B[b].s)}</div></div><div class="card"><small>Current stock</small><div class="v" style="font-size:22px;font-weight:700;color:var(--g)">${fmt(s.c)} ${p.u}</div></div></div><div class="card"><b>Stock calculation</b><br><br>${calc(s)}</div><div class="card" style="margin-top:16px"><b>Batch history</b><br><br><div class="tl">${ev.map(m=>{const sg=m[2]=='D'?-1:m[2]=='X'?0:1;bal+=sg*m[3];return`<div style="--c:${m[2]=='D'?'var(--p)':m[2]=='X'?'var(--r)':m[2]=='P'?'var(--b)':'var(--g)'}"><small>${dt(m[0])}</small><br>${tb(m[2])} <b>${sg?(sg>0?'+':'−')+fmt(m[3]):fmt(m[3])+' (excluded)'} ${p.u}</b> <small>${m[4]}</small></div>`}).join('')}<div style="--c:var(--ink)"><b>Current balance: ${fmt(s.c)} ${p.u}</b></div></div></div>`}
function moves(){const r=M.filter(m=>(!mt||m[2]==mt)&&(!q||m[1].includes(q.toUpperCase()))).sort((a,b)=>a[0]<b[0]?1:-1);return`<div class="hd"><h2>Stock Movements</h2></div><div class="card"><div class="fl"><input type="date"><input placeholder="Batch" oninput="q=this.value;go(1)"><select onchange="mt=this.value;go(1)"><option value="">All movement types</option>${Object.keys(TYPE).map(t=>`<option value="${t}" ${mt==t?'selected':''}>${TYPE[t][0]}</option>`)}</select></div>${dtable(['Date','Product','Batch No.','Movement','Quantity','Unit','Source / Destination','User','Details'],r.map(m=>[dt(m[0]),pr(m[1]).n,m[1],tb(m[2]),(m[2]=='D'?'−':m[2]=='X'?'':'+')+fmt(m[3]),pr(m[1]).u,m[4],m[5],`<a href="#/batch/${m[1]}">View movement details</a>`]),'movement')}</div>`}
const RP=['Daily Production Report','Stock Report','Monthly Report','Distribution Report','Returns Report'];
function reports(){return`<div class="hd"><h2>Reports</h2></div><div class="kpis" style="grid-template-columns:repeat(auto-fit,minmax(280px,1fr))">${RP.map(r=>`<div class="card"><b>${r}</b><p style="color:var(--mut)">${['Date, product, batch, quantity, status','Opening, production, returns, available, distribution, closing','Period totals from opening to closing','Date, product, batch, quantity, destination','Date, product, batch, source, reason, condition'][RP.indexOf(r)]}</p><div class="fl"><button class="btn sm" onclick="location.hash='#/report'">View Report</button><button class="btn s sm" onclick="print()">Print</button><button class="btn s sm" onclick="toast('PDF export started.')">Export PDF</button><button class="btn s sm" onclick="toast('Excel export started.')">Export Excel</button></div></div>`).join('')}</div>`}
function report(){const a=Object.keys(B).map(b=>st(b)),S=k=>a.reduce((x,s)=>x+s[k],0);return`<div class="hd noprint"><h2>Report preview</h2><div><button class="btn" onclick="print()">Print</button> <button class="btn s" onclick="toast('PDF export started.')">Export PDF</button></div></div><div class="rp"><b style="letter-spacing:.04em">HERBAL PRODUCTION & STOCK MANAGEMENT SYSTEM</b><h2 style="margin:4px 0">Monthly Stock Report</h2><div>Herbal Production Department · Period: <b>September 2026</b><br>Generated: 30 Sep 2026 by ${ME}</div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:16px 0">${[['Opening',S('o')],['Production',S('p')],['Returns',S('r')],['Available',S('av')],['Distribution',S('d')],['Closing',S('c')]].map(x=>`<div style="border:1px solid #ccc;border-radius:8px;padding:8px"><small>${x[0]}</small><br><b style="font-size:18px">${fmt(x[1])}</b></div>`).join('')}</div>${stockTable(stockRows(()=>1),0).replace(/class="tw"/,'')}<div class="sig"><div>Prepared by</div><div>Supervisor approval</div></div></div>`}
function profile(){return`<div class="hd"><h2>User Profile</h2></div><div class="card" style="max-width:560px"><div class="fg"><label>Name<input value="Admin User"></label><label>Role<select><option>Stock Officer</option><option>Administrator</option><option>Supervisor</option></select></label><label class="w">Email<input value="admin@herbalstock.example"></label></div><div class="act"><button class="btn" onclick="toast('Profile saved successfully.')">Save changes</button></div></div>`}
function settings(){return`<div class="hd"><h2>Settings</h2></div><div class="card" style="max-width:560px"><b>Distribution destinations</b><p>${DEST.map(d=>`<span class="bd gr">${d}</span>`).join(' ')}</p><div class="fl"><input id="nd" placeholder="New destination"><button class="btn" onclick="if($('#nd').value){DEST.push($('#nd').value);toast('Destination added.');go()}">Add destination</button></div><hr style="border:0;border-top:1px solid var(--line)"><b>Data</b><p style="color:var(--mut)">Records are stored in this browser only.</p><button class="btn d sm" onclick="resetData()">Reset to sample data</button><hr style="border:0;border-top:1px solid var(--line)"><b>Roles</b><p style="color:var(--mut)">Administrator: manage users, products, locations, adjustments. Stock Officer: record stock movements and reports. Supervisor: view and review records.</p></div>`}
function login(){return`<div class="login"><div class="lv"><div class="logo"><i>${leaf}</i><div><b>HERBAL STOCK</b></div></div><h2>Every batch accounted for, from production to closing stock.</h2><p style="opacity:.8">Opening → Production → Usable Returns → Available → Distribution → Closing</p></div><div class="lf"><div class="fg"><h2 style="margin:0">HERBAL PRODUCTION & STOCK MANAGEMENT</h2><label>Email / Username<input placeholder="you@company.com" value="admin"></label><label>Password<input type="password" value="password"></label><label><input type="checkbox" style="width:auto"> Remember me</label><button class="btn" onclick="location.hash='#/dashboard'">Sign in</button><a href="#">Forgot password?</a></div></div></div>`}
function go(keep){persist();if(!keep){}const h=location.hash.slice(2).split('/'),pg=h[0]||'dashboard';if(pg=='login')return $('#app').innerHTML=login();const V={dashboard:['Dashboard',dash],products:['Products',prods],opening:['Opening Stock',opening],production:['Production',()=>rec(mtable(['P'],['Date','Product','Batch','Quantity','Unit','Status','Recorded By','Actions']),0,'Production','fpd')],distribution:['Distribution',()=>rec(mtable(['D'],['Date','Product','Batch','Quantity','Unit','Destination','Recorded By','Status']),0,'Distribution','fd')],returns:['Returns',()=>rec(mtable(['R','X'],['Date','Product','Batch','Quantity','Unit','Source · Condition','','Condition','Stock Effect']),0,'Returns','fr')],stock:['Stock / Inventory',stock],movements:['Stock Movements',moves],reports:['Reports',reports],report:['Report Preview',report],profile:['User Profile',profile],settings:['Settings',settings],batch:['Batch '+(h[1]||''),()=>batch(h[1])]}[pg]||['Dashboard',dash];const fo=document.activeElement,id=fo&&fo.tagName=='INPUT'&&!fo.id?fo.placeholder:null,pos=fo?.selectionStart;$('#app').innerHTML=shell(V[0],V[1]());if(id){const n=[...document.querySelectorAll('input')].find(i=>i.placeholder==id&&!i.id);if(n){n.focus();n.setSelectionRange(pos,pos)}}}

// ---- Persistence (browser localStorage, static app: no backend) ----
const KEY='herbalstock.v1';
(function load(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(!d)return;
M=d.M;PR.splice(0,PR.length,...d.PR);DEST.splice(0,DEST.length,...d.DEST);
Object.keys(B).forEach(k=>delete B[k]);Object.assign(B,d.B)}catch(e){}})();
function persist(){try{localStorage.setItem(KEY,JSON.stringify({M,PR,DEST,B}))}catch(e){}}
function resetData(){if(confirm('Reset all data to the sample records?')){localStorage.removeItem(KEY);location.reload()}}
addEventListener('hashchange',()=>{q='';fp='';mt='';go()});if(!location.hash)location.hash='#/login';go();